### ISSUE TITLE
Add flexibility for easily turning on DEBUG mode

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/MOM6-interface#4]
In compile.sh repro=1 is hard-coded.  REPRO and DEBUG cannot both be turned on.  We need to add a capability to have debug easily turned on.

**Comment by jiandewang** [comment]
agree, compile.sh was developed in the early stage when I was testing standard alone MOM6 and MOM6-examples, now it is time for us to standarize it in UFS.

**Comment by DeniseWorthen** [comment]
Resolved by PR #7, #8
